version: '3.7'
  
services:
  web:
    build: docker/apache
    volumes: [ ./src:/var/www/html ]
    ports: [ 8080:80 ]
  db:
    build: docker/mysql
    volumes: [ php-sandbox-db:/var/lib/mysql ]
    
volumes:
  php-sandbox-db:

